/* -------- Generated by guess_target() ----------- */
#ifndef BEYE_CONFIG_ARCH
#define BEYE_CONFIG_ARCH 1
#define ARCH_X86 1
#define __CPU__ athlon
/* Define if your processor stores words with the most significant
   byte first (like Motorola and SPARC, unlike Intel and VAX).  */
#undef WORDS_BIGENDIAN
#define TARGET_LINUX 1
#define SLIBSUFFIX ".so"
#define ARCH_X86_32 1
/* Extension defines */
#define FPU_CLOBBERED "st","st(1)","st(2)","st(3)","st(4)","st(5)","st(6)","st(7)"
#define MMX_CLOBBERED "mm0","mm1","mm2","mm3","mm4","mm5","mm6","mm7"
#define SSE_CLOBBERED "xmm0","xmm1","xmm2","xmm3","xmm4","xmm5","xmm6","xmm7"
#endif /* BEYE_CONFIG_ARCH */
#define USE_FASTCALL 1
#define USE_CONSTFUNC 1
#define USE_PUREFUNC 1
#define __DEFAULT_DISASM 0
#define CAN_COMPILE_X86_GAS 1
#define HAVE_PPACK 1
#define HAVE_TERMINAL_OUT 1
#define HAVE_BACKTRACE 1
#define HAVE_POPEN 1
#define HAVE_PCLOSE 1
#define HAVE_SYS_RESOURCE_H 1
#define HAVE_MMAP 1
#define HAVE_MPROTECT 1
#undef HAVE_ENDIAN_H
#undef HAVE_BYTESWAP_H
#define HAVE_ICONV 1
#define HAVE_MEMALIGN 1
#define HOST "i686-pc-linux-gnu"

#ifndef HAVE_ENDIAN_H
#define __BYTE_ORDER __LITTLE_ENDIAN
#endif

/* Defined to some form of __attribute__ ((...)) if the compiler supports
   a different, more efficient calling convention.  */
#if defined ( USE_FASTCALL )
#if defined ( __i386__ )
/* define internal_function __attribute__ ((regparm (3), stdcall)) */
# define __FASTCALL__ __attribute__ ((regparm (3)))
#else
/* define internal_function __attribute__ ((regparm (6), stdcall)) */
# define __FASTCALL__ __attribute__ ((regparm (6)))
#endif
#else
# define __FASTCALL__
#endif

#if defined ( USE_CONSTFUNC )
/* Example: sin(), cos() */
# define __CONST_FUNC__ __attribute__ ((const))
#else
# define __CONST_FUNC__
#endif

#if defined ( USE_PUREFUNC )
/* Example: strlen(), memcmp() */
# define __PURE_FUNC__ __attribute__ ((pure))
#else
# define __PURE_FUNC__
#endif

typedef void any_t;

/* Removes warning about unused arguments */
# define UNUSED(x) ((any_t)(x))

/* Physical size of page on this system */
#define __VM_PAGE_SIZE__ 4096
#if defined(__GNUC__) && (__GNUC__ > 3 || __GNUC__ == 3 && __GNUC_MINOR__ > 0)
#define __PAGE_ALIGNED__ __attribute__ ((aligned (__VM_PAGE_SIZE__)))
#else
#define __PAGE_ALIGNED__
#endif

/* Compile-time random numbers */
#define RND_CHAR0 140
#define RND_CHAR1 189
#define RND_CHAR2 189
#define RND_CHAR3 192
#define RND_CHAR4 88
#define RND_CHAR5 124
#define RND_CHAR6 253
#define RND_CHAR7 188
#define RND_CHAR8 180
#define RND_CHAR9 144

#define RND_NUMBER0 964375957
#define RND_NUMBER1 111439521
#define RND_NUMBER2 230947363
#define RND_NUMBER3 1091768740
#define RND_NUMBER4 1184290310
#define RND_NUMBER5 1952165342
#define RND_NUMBER6 533682794
#define RND_NUMBER7 1498717580
#define RND_NUMBER8 1981649360
#define RND_NUMBER9 140524647

#define RND_STR0 "x1332068635"
#define RND_STR1 "x344206338"
#define RND_STR2 "x1492401621"
#define RND_STR3 "x498310506"
#define RND_STR4 "x1054924504"
#define RND_STR5 "x589710420"
#define RND_STR6 "x837665885"
#define RND_STR7 "x1722012372"
#define RND_STR8 "x1603331802"
#define RND_STR9 "x608318101"


#define RND_RENAME0(a) a ## 433481758
#define RND_RENAME1(a) a ## 2076514474
#define RND_RENAME2(a) a ## 1055804720
#define RND_RENAME3(a) a ## 1267980139
#define RND_RENAME4(a) a ## 456860392
#define RND_RENAME5(a) a ## 1525364957
#define RND_RENAME6(a) a ## 446722840
#define RND_RENAME7(a) a ## 1298835630
#define RND_RENAME8(a) a ## 346367796
#define RND_RENAME9(a) a ## 300458403

#define SECURE_NAME0(a) x1332068635
#define SECURE_NAME1(a) x344206338
#define SECURE_NAME2(a) x1492401621
#define SECURE_NAME3(a) x498310506
#define SECURE_NAME4(a) x1054924504
#define SECURE_NAME5(a) x589710420
#define SECURE_NAME6(a) x837665885
#define SECURE_NAME7(a) x1722012372
#define SECURE_NAME8(a) x1603331802
#define SECURE_NAME9(a) x608318101
